"""Six

Revision ID: 4d18b406c95b
Revises: 54a9b6772e59
Create Date: 2022-05-17 10:05:11.155733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d18b406c95b'
down_revision = '54a9b6772e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
