"""Five

Revision ID: 54a9b6772e59
Revises: fde12ddbba17
Create Date: 2022-05-17 09:46:00.052475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a9b6772e59'
down_revision = 'fde12ddbba17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
