"""Four

Revision ID: fde12ddbba17
Revises: bded8fd39448
Create Date: 2022-05-17 09:42:08.481039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde12ddbba17'
down_revision = 'bded8fd39448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
